Repository PlaceOS/init, pull requests merged in 2022-04, with the labels that each got.

#60 chore: bump placeos-models to 8.1.0
  shard.lock
  shard.yml
Labels: type: chore

#59 refactor(metadata): migrate Metadata.details to JSON
  src/migrations/1.2204-000-metadata_details_json.cr
Labels: type: refactor

#61 feat(migration): ensure user id prefixed by user table name
  src/migrations/1.2204-001-user_id_prefix.cr
Labels: type: enhancement

#62 fix(migrations/1.2204-001-user_id_prefix): don't use model validation
  shard.lock
  src/migrations/1.2204-001-user_id_prefix.cr
Labels: type: bug

#63 fix(migrations/user-id-prefix): solves issue with changing primary key
  src/migrations/1.2204-001-user_id_prefix.cr
Labels: type: bug
